# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f76c99d9c19ccdd369f00754fd33510ef6bf4dd13142e96f4ac20c76e66c82e7e6dcc76c8c3f67a3a5395653040d3e851bf449b474ec2e8361da61c90cd6790

test:
  secret_key_base: 64aec3463ac199e0801aeaf8fadf08e44773418833baf640f185784ec078e4b10c46b0b13f50172cc57082e3f993ec6e2babf68573a4ab3de58a9c518d6c7f28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
